#!/bin/bash

# Copyright (c) 2026 Alex313031.

export HERE=${PWD} &&

export TOOLS_PATH=${HERE}/tools &&
export MINGW_PATH=${HERE}/tools/mingw/linux/x64/bin &&

export PATH=${MINGW_PATH}:${TOOLS_PATH}:$PATH:${TOOLS_PATH}:${MINGW_PATH} &&

${TOOLS_PATH}/ninja $@
